/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularioprincipal;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import conexionSQL.conexionSQL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;


/**
 *
 * @author Pc gamer
 */
public class distribuidores extends javax.swing.JInternalFrame {
    
   conexionSQL cc=new conexionSQL();
   Connection con=cc.conexion();

    /**
     * Creates new form distribuidores
     */
    public distribuidores() {
        initComponents();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtañoregistro = new javax.swing.JTextField();
        txtrut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDistribuidores = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRO DE DISTRIBUIDORES");

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("dsitribuidores");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setText("Nombre Distribuidor");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Año Registro");

        jLabel3.setText("RUT");

        txtañoregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañoregistroActionPerformed(evt);
            }
        });

        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtañoregistro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtañoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addGap(26, 26, 26))
        );

        tablaDistribuidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDistribuidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDistribuidoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDistribuidores);

        jLabel4.setText("Busqueda");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 456, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 456, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(114, 114, 114)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 204, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 205, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(339, 339, 339)))
                    .addGap(22, 22, 22)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      limpiarCajas();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    insertarDatos();
    limpiarCajas();
    mostrarDatos();

    }//GEN-LAST:event_btnGuardarActionPerformed

  public void limpiarCajas(){
    // ACA INGRESO EL CODIGO PARA LIMPIAR LAS  CAJAS LUEGO DE UN INGRESO DE DATOS ///
    
    /// reliazo luego de caDa registro los espacios vuleva blanco otra vez 
    txtNombre.setText("");
    txtañoregistro.setText("");
    txtrut.setText("");
   
    
            
}     
    
    public void mostrarDatos(){
 // MUESTRO LOS DATOS DE LOS REGISTROS ///    
    
    String[] titulos={"ID","Nombre Distribuidor","Año de Registro","RUT"};
    String[] registros=new  String[5];
    
    DefaultTableModel modelo=new DefaultTableModel(null,titulos);
    
    
    String SQL="select * from distribuidores";
    
    try {
        
        
        Statement st=(Statement) con.createStatement();
        ResultSet rs=st.executeQuery(SQL);
        
        while (rs.next()){
            
            
        registros[0]=rs.getString("iddistribuidores");
        registros[1]=rs.getString("nombre");
        registros[2]=rs.getString("añoregistro");
        registros[3]=rs.getString("rut");
        
        
        
      modelo.addRow(registros);
        
         
        }
        
        tablaDistribuidores.setModel(modelo);
    } catch  (Exception e)  {
        
        JOptionPane.showMessageDialog(null,"Error al mostrar Datos"+ e.getMessage());
    }
       
}
    
    
   
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarRegistros();
        mostrarDatos();
        limpiarCajas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       ActualizarDatos();
        limpiarCajas();
        mostrarDatos(); 

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaDistribuidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDistribuidoresMouseClicked

        int filaSeleccionada=tablaDistribuidores.rowAtPoint(evt.getPoint());

        txtNombre.setText(tablaDistribuidores.getValueAt(filaSeleccionada,1).toString());
        txtañoregistro.setText(tablaDistribuidores.getValueAt(filaSeleccionada,2).toString());
       txtrut.setText(tablaDistribuidores.getValueAt(filaSeleccionada,3).toString());

    }//GEN-LAST:event_tablaDistribuidoresMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        filtrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        filtrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtañoregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañoregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtañoregistroActionPerformed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutActionPerformed

    
    
    public void insertarDatos(){
    
        try {
            
            String SQL="insert into distribuidores (nombre,añoregistro,rut) values (?,?,?)";
            
            PreparedStatement pst=(PreparedStatement) con.clientPrepareStatement(SQL);
            
            
            //nombre de libro//
            pst.setString(1,txtNombre.getText());
            
            pst.setString(2,txtañoregistro.getText());
            
            pst.setString(3,txtrut.getText());
            
           
      
           pst.execute();
           
           JOptionPane.showMessageDialog(null,"registro exitoso");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de registro" +e.getMessage());
        }
        
        
    }
    
    
    public void ActualizarDatos(){
    
        try {
            
            String SQL=" update distribuidores set nombre=?,añoregistro=?,rut=? where iddistribuidores=? ";
            
            
            int filaSeleccionado=tablaDistribuidores.getSelectedRow();
            String dao=(String)tablaDistribuidores.getValueAt(filaSeleccionado, 0);
            
            PreparedStatement pst=(PreparedStatement) con.clientPrepareStatement(SQL);
            
            
            //nombre de libro//
            pst.setString(1,txtNombre.getText());
            
            pst.setString(2,txtañoregistro.getText());
            
            pst.setString(3,txtrut.getText());
            
          
        
           
           pst.setString(4, dao);
           pst.execute();
           
           JOptionPane.showMessageDialog(null,"Registro editado con exito");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de edicion" +e.getMessage());
        }
        
        
    }
    
    public void eliminarRegistros(){
        
        int filaSeleccionada=tablaDistribuidores.getSelectedRow();
        
        try {
            String SQL="delete from distribuidores where iddistribuidores="+tablaDistribuidores.getValueAt(filaSeleccionada,0);
            
            
            Statement st=(Statement) con.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            
            if (n>=0) {
                JOptionPane.showMessageDialog(null,"Registro Eliminado");
                
            }
             
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error al eliminar registro"+e.getMessage());
                    
        }
         
    }
    
    public void filtrarDatos(String valor){
    // ACA INGRESO EL FILTRO DE LA BARRA BUSCAR /// 
    
    
    String[] titulos={"ID","Nombre ","añoregistro","rut"};
    String[] registros=new  String[5];
    
    DefaultTableModel modelo=new DefaultTableModel(null,titulos);
    
    
    String SQL="select * from distribuidores where nombre like '%"+valor+"%'";
    
    try {
        
        
        Statement st=(Statement) con.createStatement();
        ResultSet rs=st.executeQuery(SQL);
        
        while (rs.next()){
            
            
        registros[0]=rs.getString("iddistribuidores");
        registros[1]=rs.getString("nombre");
        registros[2]=rs.getString("añoregistro");
        registros[3]=rs.getString("rut");
        
        
        
      modelo.addRow(registros);
        
         
        }
        
        tablaDistribuidores.setModel(modelo);
    } catch  (Exception e)  {
        
        JOptionPane.showMessageDialog(null,"Error al mostrar Datos"+ e.getMessage());
    }
       
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDistribuidores;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtañoregistro;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables


    
}
